### ISSUE TITLE
When will this paper be accessible?

### ISSUE THREAD

**Issue by Doragd** [TianduoWang/DiffAug#1]
Hi, I'm Gordon Lee.
Thanks for your excellent work on sentence representation learning (SRL).
I would like to know when this paper will be accessible.
By the way, I am working on collecting the SRL paper list with the unsupervised STS leaderboard.
If you are interested, you can access the following repo:
https://github.com/Doragd/Awesome-Sentence-Embedding/

I will add your paper to our paper list soon :P

**Comment by TianduoWang** [comment]
Hi Gordon,

Thanks for your interest. We are still working on revising the paper for camera-ready. We will inform you once it is accessible!

**Comment by Doragd** [comment]
Thanks~
I wonder to know what is the setting of STS in your paper.
Unsupervised? Semi-Supervised? or Supervised?
From the readme,  I can see the supervised results.

**Comment by TianduoWang** [comment]
The main idea of our paper is to learn an effective data augmentation module by training on the NLI data. Hence, we only consider semi-supervised and supervised settings.

**Comment by Doragd** [comment]
Thanks
